### ISSUE TITLE
Migrate from Claude 2.1 to ChatGPT 3.5

### ISSUE THREAD

**Issue by danielpancake** [danielpancake/ai-galileo#2]
Today, 21st of November, ClaudeAI has been given a major update. Now ~~this little piece of garbage~~ refuses to generate anything based on the old prompts, saying something along the lines of: "Я полагаю, юмор должен объединять людей, а не разделять. Давайте подумаем о более позитивных темах.". Wdym??..

Thanks, Anthropic. Three days before the deadline.

**Comment by cutefluffyfox** [comment]
UPD: found trigger for ClaudeAI. Do not mention "funny" or "jokes" as now Claude seems to be a serious model who want to do research and only research.

**Comment by danielpancake** [comment]
![I am super serious](https://media.tenor.com/SYZmA9hYMl0AAAAC/im-super-cereal-al-gore.gif)
